version: 2.1
orbs:
  node: circleci/node@4.2.1
jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Chrome
          command: $ProgressPreference = "SilentlyContinue"; $Path = $env:TEMP; $Installer = "chrome_installer.exe"; Invoke-WebRequest "http://dl.google.com/chrome/install/375.126/chrome_installer.exe" -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args "/silent /install" -Verb RunAs -Wait; Remove-Item $Path\$Installer
      - run:
          name: install packages
          command: npm i
      - run:
          name: Run Tests
          command: npm run test

workflows:
  orb-free-workflow:
    jobs:
      - test
